openapi: 3.0.3
info:
  title: Resume Screening System API
  description: API documentation for the Resume Screening Microservices
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local Development Server

paths:
  /parse-resume:
    post:
      summary: Extracts and parses text from a resume file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully parsed resume
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  experience:
                    type: array
                    items:
                      type: string
                  skills:
                    type: array
                    items:
                      type: string
                  education:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid file format

  /keyword-matching:
    post:
      summary: Matches resume data against a job description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resume_text:
                  type: string
                job_description:
                  type: string
      responses:
        '200':
          description: Keyword matching result
          content:
            application/json:
              schema:
                type: object
                properties:
                  similarity_score:
                    type: number
                    format: float
        '400':
          description: Invalid input data

  /score-resume:
    post:
      summary: Scores and ranks a resume based on job criteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parsed_resume:
                  type: object
                job_description:
                  type: object
      responses:
        '200':
          description: Resume scoring results
          content:
            application/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
                    format: float
        '400':
          description: Invalid request payload

  /check-duplicate:
    post:
      summary: Checks if a resume is a duplicate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resume_text:
                  type: string
      responses:
        '200':
          description: Duplicate check results
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_duplicate:
                    type: boolean
        '400':
          description: Invalid input data
